# Generated by Django 4.0.3 on 2022-04-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код банка')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('address', models.CharField(max_length=60, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='BS',
            fields=[
                ('kod', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='Код счета')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Бухгалтерские счета',
            },
        ),
        migrations.CreateModel(
            name='FO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(choices=[('ТОО', 'Товарищество с ограниченной ответственностью'), ('ИП', 'Индивидуальный предприниматель'), ('ООО', 'Общество с ограниченной ответственностью'), ('АО', 'Акционерное общество'), ('ЗАО', 'Закрытое акционерное общество')], max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Формы организации',
            },
        ),
        migrations.CreateModel(
            name='NK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код комитета')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('address', models.CharField(max_length=60, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Налоговые комитеты',
            },
        ),
        migrations.CreateModel(
            name='Predpriyatie',
            fields=[
                ('bin_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='БИН')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='Полное наименование')),
                ('sh_name', models.CharField(max_length=50, unique=True, verbose_name='Сокращенное наименование')),
                ('address', models.CharField(max_length=60, unique=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Телефон')),
                ('fio_ruk', models.CharField(max_length=50, unique=True, verbose_name='ФИО руководителя')),
                ('date', models.DateField(verbose_name='Дата постановки на учет')),
                ('chislo_rab', models.PositiveIntegerField(verbose_name='Число работников')),
                ('uchrediteli', models.CharField(max_length=200, unique=True, verbose_name='Учредители')),
                ('form_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.fo', verbose_name='Код формы организации')),
                ('nalog_kom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.nk', verbose_name='Код налогового комитета')),
            ],
            options={
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='VHD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код вида хозяйственной деятельности')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Виды хозяйственной деятельности',
            },
        ),
        migrations.CreateModel(
            name='PVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_pvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie', verbose_name='БИН')),
                ('vid_hoz_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.vhd', verbose_name='Код вида хозяйственной деятельности')),
            ],
            options={
                'verbose_name_plural': 'Предприятия_виды деятельности',
            },
        ),
        migrations.AddField(
            model_name='predpriyatie',
            name='vid_hoz_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.vhd', verbose_name='Код основного вида хозяйственной деятельности'),
        ),
        migrations.CreateModel(
            name='PB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schet', models.CharField(max_length=20, unique=True, verbose_name='Лицевой счет')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.bank', verbose_name='Код банка')),
                ('bin_pb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie', verbose_name='БИН')),
            ],
            options={
                'verbose_name_plural': 'Предприятия_банки',
            },
        ),
        migrations.CreateModel(
            name='FP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvartal', models.CharField(choices=[('Первый', '1'), ('Второй', '2'), ('Третий', '3'), ('Четвертый', '4')], max_length=50, verbose_name='Квартал')),
                ('date', models.IntegerField(verbose_name='Год')),
                ('summa', models.PositiveIntegerField(verbose_name='Сумма')),
                ('priznak', models.CharField(choices=[('Дебет', 'Дт'), ('Кредит', 'Кт')], max_length=50, verbose_name='Признак')),
                ('bin_fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.predpriyatie', verbose_name='БИН')),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.bs', verbose_name='Код счета')),
            ],
            options={
                'verbose_name_plural': 'Финансовые показатели',
            },
        ),
    ]
