# Generated by Django 4.0.3 on 2022-04-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb',
            name='bin_pb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predpriyatie', to='WebApp.predpriyatie', verbose_name='БИН'),
        ),
    ]
