# Generated by Django 4.0.3 on 2022-04-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_pb_bin_pb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='priznak',
            field=models.CharField(choices=[('Кт', 'Дебет'), ('Дт', 'Кредит')], max_length=50, verbose_name='Признак'),
        ),
    ]
