# Generated by Django 4.0.3 on 2022-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_fp_priznak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='priznak',
            field=models.CharField(choices=[('Дебет', 'Дт'), ('Кредит', 'Кт')], max_length=50, verbose_name='Признак'),
        ),
    ]
